Makefile.rocq : _RocqProject
	@ rocq makefile -f $< -o $@

ifeq (,$(filter $(targets_norocq),$(MAKECMDGOALS)))
-include Makefile.rocq
endif

.PHONY : clean
clean ::
	@ rm -f Makefile.rocq Makefile.rocq.conf
