(* This file was generated by ocaml2zoo. *)

Require Import zoo_demo.example__code.

#[global] Opaque example٠example1.
#[global] Opaque example٠example2.
#[global] Opaque example٠example3.
#[global] Opaque example٠example4.
