(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Definition example٠example1 : val :=
  𝗿𝗲𝗰 "example1" "param" ->
    𝗺𝗮𝘁𝗰𝗵 "param" 𝘄𝗶𝘁𝗵
    | [] ->
        0
    | "x" :: "l" ->
        "x" + "example1" "l"
    𝗲𝗻𝗱.

Notation "'example٠Nil'" := (
  in_type "zoo_demo.example.t1" Tag0
)(in custom zoo_tag
).
Notation "'example٠Cons'" := (
  in_type "zoo_demo.example.t1" Tag1
)(in custom zoo_tag
).

Definition example٠example2 : val :=
  𝗿𝗲𝗰 "example2" "param" ->
    𝗺𝗮𝘁𝗰𝗵 "param" 𝘄𝗶𝘁𝗵
    | example٠Nil ->
        0
    | example٠Cons "x" "l" ->
        "x" + "example2" "l"
    𝗲𝗻𝗱.

Notation "'example٠fst'" := (
  in_type "zoo_demo.example.t2" 0
)(in custom zoo_proj
).
Notation "'example٠snd'" := (
  in_type "zoo_demo.example.t2" 1
)(in custom zoo_proj
).

Definition example٠example3 : val :=
  𝗳𝘂𝗻 "t" ->
    "t".<example٠fst> + "t".<example٠snd>.

Notation "'example٠f1'" := (
  in_type "zoo_demo.example.t3" 0
)(in custom zoo_field
).
Notation "'example٠f2'" := (
  in_type "zoo_demo.example.t3" 1
)(in custom zoo_field
).

Definition example٠example4 : val :=
  𝗳𝘂𝗻 "t" ->
    "t" <-{example٠f1} "t".{example٠f1} + "t".{example٠f2}.
